[package]
name = "sps-fi"
version = "0.1.0"
authors = ["D. Galagan galagan.dm@gmail.com"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = "4.0.0"
near-contract-standards = "4.0.0-pre.2"